# Generated by Django 5.2.6 on 2025-11-25 00:25

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('tenancy', '0020_remove_contactgroupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtnFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('fault_number', models.CharField(max_length=20, unique=True)),
                ('fault_occurrence_time', models.DateTimeField()),
                ('fault_recovery_time', models.DateTimeField(blank=True, null=True)),
                ('fault_category', models.CharField(max_length=20)),
                ('interruption_reason', models.CharField(max_length=30)),
                ('fault_details', models.TextField()),
                ('duty_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otn_faults', to=settings.AUTH_USER_MODEL)),
                ('interruption_location', models.ManyToManyField(related_name='otn_faults', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'OTN故障',
                'verbose_name_plural': 'OTN故障',
                'ordering': ('-fault_occurrence_time',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OtnFaultImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('service_interruption_time', models.DateTimeField()),
                ('service_recovery_time', models.DateTimeField(blank=True, null=True)),
                ('impacted_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otn_fault_impacts', to='tenancy.tenant')),
                ('otn_fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='netbox_otnfaults.otnfault')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '故障影响业务',
                'verbose_name_plural': '故障影响业务',
                'ordering': ('-service_interruption_time',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
