# Generated by Django manually for GPS fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='interruption_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS坐标（十进制格式, xx.yyyyyy）', max_digits=8, null=True, verbose_name='中断位置纬度'),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='interruption_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS坐标（十进制格式, xx.yyyyyy）', max_digits=9, null=True, verbose_name='中断位置经度'),
        ),
    ]
