# Generated by Django manually to fix all null constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0002_add_gps_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otnfault',
            name='fault_category',
            field=models.CharField(blank=True, choices=[('power', '电力故障', 'orange'), ('fiber', '光缆故障', 'red'), ('pigtail', '尾纤故障', 'blue'), ('device', '设备故障', 'green'), ('other', '其他故障', 'gray')], max_length=20, null=True, verbose_name='故障分类'),
        ),
        migrations.AlterField(
            model_name='otnfault',
            name='interruption_reason',
            field=models.CharField(blank=True, choices=[('road_construction', '道路施工'), ('sabotage', '人为破坏'), ('line_rectification', '线路整改'), ('misoperation', '误操作'), ('power_supply', '供电故障'), ('municipal_construction', '市政施工'), ('rodent_damage', '鼠害'), ('natural_disaster', '自然灾害')], max_length=30, null=True, verbose_name='中断原因'),
        ),
        migrations.AlterField(
            model_name='otnfault',
            name='fault_details',
            field=models.TextField(blank=True, null=True, verbose_name='故障及处置详情'),
        ),
    ]
