# Generated by Django manually to add tags fields
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0004_fix_all_null_constraints'),
        ('extras', '0077_customlink_extend_text_and_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='otnfaultimpact',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
