# Generated by Django manually
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0005_add_tags_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='comments',
            field=models.TextField(blank=True, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='otnfaultimpact',
            name='comments',
            field=models.TextField(blank=True, verbose_name='评论'),
        ),
    ]
