# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0186_location_facility'),
        ('netbox_contract', '0043_invoice_status'),
        ('netbox_otnfaults', '0006_add_comments_fields'),
    ]

    operations = [
        # 1) 省份，引用netbox组织机构中的地区
        migrations.AddField(
            model_name='otnfault',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otn_faults', to='dcim.region', verbose_name='省份'),
        ),
        
        # 2) 紧急程度
        migrations.AddField(
            model_name='otnfault',
            name='urgency',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='low', max_length=10, verbose_name='紧急程度'),
        ),
        
        # 3) 第一报障来源
        migrations.AddField(
            model_name='otnfault',
            name='first_report_source',
            field=models.CharField(choices=[('national_backbone', '国干网网管'), ('future_network', '未来网络网管'), ('customer_support', '客户保障'), ('other', '其他')], default='other', max_length=20, verbose_name='第一报障来源'),
        ),
        
        # 4) 计划内
        migrations.AddField(
            model_name='otnfault',
            name='planned',
            field=models.BooleanField(default=False, verbose_name='计划内'),
        ),
        
        # 5) 线路主管
        migrations.AddField(
            model_name='otnfault',
            name='line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_otn_faults', to='users.user', verbose_name='线路主管'),
        ),
        
        # 6) 维护方式
        migrations.AddField(
            model_name='otnfault',
            name='maintenance_mode',
            field=models.CharField(blank=True, choices=[('outsourced', '代维'), ('coordinated', '协调'), ('self_maintained', '自维')], max_length=20, null=True, verbose_name='维护方式'),
        ),
        
        # 7) 处理单位
        migrations.AddField(
            model_name='otnfault',
            name='handling_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_otn_faults', to='netbox_contract.serviceprovider', verbose_name='处理单位'),
        ),
        
        # 8) 处理派发时间
        migrations.AddField(
            model_name='otnfault',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理派发时间'),
        ),
        
        # 9) 维修出发时间
        migrations.AddField(
            model_name='otnfault',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='维修出发时间'),
        ),
        
        # 10) 到达现场时间
        migrations.AddField(
            model_name='otnfault',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到达现场时间'),
        ),
        
        # 11) 故障修复时间
        migrations.AddField(
            model_name='otnfault',
            name='repair_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='故障修复时间'),
        ),
        
        # 13) 是否超时
        migrations.AddField(
            model_name='otnfault',
            name='timeout',
            field=models.BooleanField(default=False, verbose_name='是否超时'),
        ),
        
        # 14) 超时原因
        migrations.AddField(
            model_name='otnfault',
            name='timeout_reason',
            field=models.TextField(blank=True, null=True, verbose_name='超时原因'),
        ),
        
        # 15) 资源类型
        migrations.AddField(
            model_name='otnfault',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('self_built', '自建光缆'), ('coordinated', '协调资源'), ('leased', '租赁纤芯')], max_length=20, null=True, verbose_name='资源类型'),
        ),
        
        # 16) 光缆路由属性
        migrations.AddField(
            model_name='otnfault',
            name='cable_route',
            field=models.CharField(choices=[('highway', '高速公路'), ('non_highway', '非高速')], default='highway', max_length=20, verbose_name='光缆路由属性'),
        ),
        
        # 17) 故障处理人
        migrations.AddField(
            model_name='otnfault',
            name='handler',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='故障处理人'),
        ),
        
        # 18) 恢复方式
        migrations.AddField(
            model_name='otnfault',
            name='recovery_mode',
            field=models.CharField(blank=True, choices=[('fusion_splicing', '熔接恢复'), ('tail_fiber_replacement', '更换尾纤恢复'), ('processing', '处理恢复'), ('fiber_adjustment', '调纤恢复'), ('automatic', '自动恢复'), ('unknown', '无法查明'), ('not_provided', '未提供')], max_length=30, null=True, verbose_name='恢复方式'),
        ),
    ]
