# Generated by Django 5.2.6 on 2025-11-27 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0007_add_new_fault_fields'),
    ]

    operations = [
    ]
