# Generated by Django 5.2.6 on 2025-11-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0011_add_journaling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otnfault',
            name='first_report_source',
            field=models.CharField(max_length=20),
        ),
    ]
