# Generated by Django 5.2.6 on 2025-12-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0013_add_fault_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otnfault',
            name='planned',
        ),
    ]
