# Generated by Django 5.2.6 on 2025-12-08 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0045_alter_contract_currency_alter_invoice_currency_and_more'),
        ('netbox_otnfaults', '0014_remove_otnfault_planned'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otn_faults', to='netbox_contract.contract'),
        ),
    ]
