# Generated by Django 5.2.6 on 2025-12-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_otnfaults', '0020_otnpath'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otnfault',
            name='interruption_location',
            field=models.ManyToManyField(blank=True, related_name='otn_faults', to='dcim.site'),
        ),
        migrations.AlterUniqueTogether(
            name='otnfaultimpact',
            unique_together={('otn_fault', 'impacted_service')},
        ),
    ]
