# Generated by Django 5.2.6 on 2025-12-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0022_otnpathgroup_otnpath_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otnpath',
            name='group',
        ),
        migrations.AddField(
            model_name='otnpathgroup',
            name='paths',
            field=models.ManyToManyField(blank=True, related_name='groups', to='netbox_otnfaults.otnpath'),
        ),
    ]
