# Generated by Django 5.2.6 on 2026-01-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_otnfaults', '0023_remove_otnpath_group_otnpathgroup_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtnPathGroupSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('path_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sites', to='netbox_otnfaults.otnpathgroup')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.site')),
            ],
            options={
                'verbose_name': '路径组站点',
                'verbose_name_plural': '路径组站点',
                'ordering': ('path_group', 'position', 'pk'),
                'unique_together': {('path_group', 'site')},
            },
        ),
        migrations.AddField(
            model_name='otnpathgroup',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='path_groups', through='netbox_otnfaults.OtnPathGroupSite', to='dcim.site'),
        ),
    ]
