# Generated by Django 5.2.6 on 2026-01-23 02:31

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_otnfaults', '0024_otnpathgroupsite_otnpathgroup_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnpathgroupsite',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='otnpathgroupsite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='otnpathgroupsite',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='otnpathgroupsite',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='otnpathgroupsite',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
