# Generated by Django 5.2.6 on 2026-01-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0025_otnpathgroupsite_comments_otnpathgroupsite_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='interruption_reason_detail',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
