# Generated by Django 5.2.6 on 2026-01-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0026_otnfault_interruption_reason_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfaultimpact',
            name='secondary_faults',
            field=models.ManyToManyField(blank=True, related_name='secondary_impacts', to='netbox_otnfaults.otnfault'),
        ),
    ]
