# Generated by Django 5.2.6 on 2026-01-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0027_otnfaultimpact_secondary_faults'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='power_data_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='power_maintenance_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='power_recovery_mode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
