# Generated by Django 5.2.6 on 2026-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0028_otnfault_power_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otnfault',
            name='timeout',
            field=models.BooleanField(default=True),
        ),
    ]
