# Generated by Django 5.2.6 on 2026-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0029_alter_otnfault_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='closure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
