# Generated by Django 5.2.6 on 2026-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0030_otnfault_closure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='manager_review_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='manager_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='manager_reviewer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='noc_review_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='noc_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otnfault',
            name='noc_reviewer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
