# Generated by Django 5.2.6 on 2026-03-11 08:12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_otnfaults', '0031_otnfault_manager_review_time_and_more'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='BareFiberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '裸纤业务',
                'verbose_name_plural': '裸纤业务',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='otnfaultimpact',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='otnpathgroupsite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='otnfault',
            name='fault_number',
            field=models.CharField(error_messages={'unique': '已存在相同编号的故障记录。'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='otnpathgroup',
            name='name',
            field=models.CharField(error_messages={'unique': '已存在相同名称的路径组。'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='otnpathgroup',
            name='slug',
            field=models.SlugField(error_messages={'unique': '已存在相同缩写的路径组。'}, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='otnfaultimpact',
            constraint=models.UniqueConstraint(fields=('otn_fault', 'impacted_service'), name='unique_otn_fault_impacted_service', violation_error_message='此故障下已经有该影响业务，不能重复添加。'),
        ),
        migrations.AddConstraint(
            model_name='otnpathgroupsite',
            constraint=models.UniqueConstraint(fields=('path_group', 'site'), name='unique_path_group_site', violation_error_message='该路径组已包含选定的站点。'),
        ),
        migrations.AddField(
            model_name='barefiberservice',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='barefiberservice',
            name='tenant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bare_fiber_services', to='tenancy.tenantgroup'),
        ),
    ]
