# Generated by Django 5.2.6 on 2026-03-11 08:36

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_otnfaults', '0032_barefiberservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=50)),
                ('service_group', models.CharField(blank=True, max_length=20)),
                ('bandwidth', models.CharField(blank=True, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '电路业务',
                'verbose_name_plural': '电路业务',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
