# Generated by Django 5.2.6 on 2026-03-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_otnfaults', '0033_circuitservice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otnfaultimpact',
            name='unique_otn_fault_impacted_service',
        ),
        migrations.RemoveField(
            model_name='otnfaultimpact',
            name='impacted_service',
        ),
        migrations.AddField(
            model_name='otnfaultimpact',
            name='bare_fiber_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fault_impacts', to='netbox_otnfaults.barefiberservice'),
        ),
        migrations.AddField(
            model_name='otnfaultimpact',
            name='circuit_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fault_impacts', to='netbox_otnfaults.circuitservice'),
        ),
        migrations.AddField(
            model_name='otnfaultimpact',
            name='service_type',
            field=models.CharField(default='bare_fiber', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='otnfaultimpact',
            constraint=models.UniqueConstraint(fields=('otn_fault', 'service_type', 'bare_fiber_service', 'circuit_service'), name='unique_otn_fault_impacted_service', violation_error_message='此故障下已经有该影响业务，不能重复添加。'),
        ),
    ]
