# Generated by Django 5.2.6 on 2026-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_otnfaults', '0034_remove_otnfaultimpact_unique_otn_fault_impacted_service_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otnfaultimpact',
            name='unique_otn_fault_impacted_service',
        ),
        migrations.AddConstraint(
            model_name='otnfaultimpact',
            constraint=models.UniqueConstraint(condition=models.Q(('bare_fiber_service__isnull', False)), fields=('otn_fault', 'bare_fiber_service'), name='unique_otn_fault_bare_fiber', violation_error_message='此故障下已经有该裸纤业务，不能重复添加。'),
        ),
        migrations.AddConstraint(
            model_name='otnfaultimpact',
            constraint=models.UniqueConstraint(condition=models.Q(('circuit_service__isnull', False)), fields=('otn_fault', 'circuit_service'), name='unique_otn_fault_circuit', violation_error_message='此故障下已经有该电路业务，不能重复添加。'),
        ),
    ]
