# Generated by Django 5.2.6 on 2026-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0036_barefiberservice_billing_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barefiberservice',
            name='billing_end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barefiberservice',
            name='billing_start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
