# Generated by Django 5.2.6 on 2026-03-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0037_alter_barefiberservice_billing_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitservice',
            name='billing_end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuitservice',
            name='billing_start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuitservice',
            name='business_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_circuit_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
