# Generated by Django 5.2.6 on 2026-04-05 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0042_alter_otnfaultimpact_service_site_z'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otnfault',
            name='operations_manager',
            field=models.ManyToManyField(blank=True, related_name='managed_otn_faults_operations', to=settings.AUTH_USER_MODEL),
        ),
    ]
