# Generated by Django 5.2.6 on 2026-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0043_otnfault_operations_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitservice',
            name='is_external_business',
            field=models.BooleanField(default=False, verbose_name='\u5bf9\u5916\u4e1a\u52a1'),
        ),
    ]
