# Generated by Django 5.2.6 on 2026-04-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0046_circuitservice_special_line_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuitservice',
            options={'ordering': ('business_category', 'service_group', 'special_line_name')},
        ),
    ]
