# Generated by Django 5.2.6 on 2026-04-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0048_update_business_category_data'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE netbox_otnfaults_circuitservice ALTER COLUMN bandwidth DROP NOT NULL;"),
        migrations.RunSQL("UPDATE netbox_otnfaults_circuitservice SET bandwidth = '10000' WHERE bandwidth = '10g';"),
        migrations.RunSQL("UPDATE netbox_otnfaults_circuitservice SET bandwidth = '100000' WHERE bandwidth = '100g';"),
        migrations.RunSQL("UPDATE netbox_otnfaults_circuitservice SET bandwidth = '1000' WHERE bandwidth = 'ge';"),
        migrations.RunSQL("UPDATE netbox_otnfaults_circuitservice SET bandwidth = NULL WHERE bandwidth = '';"),
        migrations.RunSQL('ALTER TABLE netbox_otnfaults_circuitservice ALTER COLUMN bandwidth TYPE integer USING bandwidth::integer;'),
        migrations.AlterField(
            model_name='circuitservice',
            name='bandwidth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
