# Generated by Django 5.2.6 on 2026-05-11 01:14

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0063_circuitservice_extra_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otnfault',
            new_name='netbox_otnf_recover_99b0a1_gin',
            old_name='netbox_otnf_recovery_732470_gin',
        ),
        migrations.RenameIndex(
            model_name='otnfault',
            new_name='netbox_otnf_root_ca_a7bc99_gin',
            old_name='netbox_otnf_root_ca_5b58bf_gin',
        ),
        migrations.RenameIndex(
            model_name='otnfault',
            new_name='netbox_otnf_rectifi_9fc3ed_gin',
            old_name='netbox_otnf_rectifi_bac8cb_gin',
        ),
        migrations.AlterField(
            model_name='otnmappreference',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
