# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0064_rename_netbox_otnf_recovery_732470_gin_netbox_otnf_recover_99b0a1_gin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otnfault',
            name='power_maintenance_mode',
            field=models.CharField(
                blank=True,
                choices=[
                    ('outsourced', '代维'),
                    ('coordinated', '协调'),
                    ('self_maintained', '自维'),
                    ('factory_maintenance', '厂家维保'),
                ],
                max_length=20,
                null=True,
                verbose_name='供电维护方式',
            ),
        ),
    ]
