# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0065_alter_otnfault_power_maintenance_mode_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otnfault',
            name='fault_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('processing', '处理中'),
                    ('temporary_recovery', '临时恢复'),
                    ('suspended', '延后处置'),
                    ('closed', '已关闭'),
                ],
                default='processing',
                max_length=20,
                null=True,
                verbose_name='处理状态',
            ),
        ),
    ]
