# Generated by Codex on 2026-05-18

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_contract', '0045_alter_contract_currency_alter_invoice_currency_and_more'),
        ('netbox_otnfaults', '0066_alter_otnfault_fault_status_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoverTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cutover_no', models.CharField(blank=True, help_text='系统自动生成，格式为CYYYYNNNN', max_length=50, unique=True, verbose_name='割接编号')),
                ('status', models.CharField(choices=[('applying', '申请中'), ('pending_implementation', '待实施'), ('completed', '已完成'), ('cancelled', '被取消')], default='applying', max_length=32, verbose_name='状态')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记时间')),
                ('planned_cutover_time', models.DateTimeField(blank=True, help_text='列表筛选和排序使用的主计划时间。多次计划时间可记录在计划割接时间记录中。', null=True, verbose_name='计划割接时间')),
                ('planned_cutover_times', models.JSONField(blank=True, default=list, verbose_name='计划割接时间记录')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutover_tasks', to='dcim.region', verbose_name='省份')),
                ('cutover_location', models.TextField(verbose_name='割接具体地点')),
                ('cutover_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='割接位置经度')),
                ('cutover_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='割接位置纬度')),
                ('related_customers', models.JSONField(blank=True, default=list, verbose_name='关联用户')),
                ('cutover_reason', models.TextField(verbose_name='割接原因')),
                ('resource_type', models.CharField(blank=True, choices=[('self_built', '自建光缆'), ('coordinated', '协调资源'), ('leased', '租赁纤芯')], max_length=20, verbose_name='光纤来源')),
                ('cable_route', models.CharField(blank=True, choices=[('highway', '高速公路'), ('non_highway', '非高速')], max_length=20, verbose_name='光缆路由属性')),
                ('resource_owner', models.CharField(blank=True, choices=[('headquarters', '本部'), ('zhejiang', '浙江子公司'), ('shaanxi', '陕西子公司'), ('sichuan', '四川子公司'), ('inner_mongolia', '内蒙古子公司'), ('jiangxi', '江西子公司'), ('shandong', '山东子公司')], max_length=30, verbose_name='资源所有者')),
                ('maintenance_mode', models.CharField(blank=True, choices=[('outsourced', '代维'), ('coordinated', '协调'), ('self_maintained', '自维'), ('leased_owned', '租赁自带')], max_length=20, verbose_name='维护方式')),
                ('management_unit', models.CharField(choices=[('headquarters', '本部'), ('zhejiang', '浙江子公司'), ('shaanxi', '陕西子公司'), ('sichuan', '四川子公司'), ('inner_mongolia', '内蒙古子公司'), ('jiangxi', '江西子公司'), ('shandong', '山东子公司'), ('third_party', '第三方')], max_length=30, verbose_name='割接管理单位')),
                ('management_unit_name', models.CharField(blank=True, max_length=100, verbose_name='割接管理单位名称')),
                ('maintenance_unit', models.CharField(blank=True, max_length=100, verbose_name='维护单位')),
                ('implementation_unit', models.CharField(max_length=100, verbose_name='割接实施单位')),
                ('cutover_contact', models.CharField(max_length=100, verbose_name='割接联系人')),
                ('cutover_contact_phone', models.CharField(max_length=50, verbose_name='割接联系人电话')),
                ('customer_approval_result', models.CharField(blank=True, choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '未批准'), ('partially_approved', '部分批准'), ('not_required', '无需审核')], max_length=32, verbose_name='客户审核结果')),
                ('customer_approval_detail', models.JSONField(blank=True, default=list, verbose_name='客户审核明细')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='割接开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='割接完成时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='割接封包时间')),
                ('is_timeout', models.CharField(choices=[('yes', '是'), ('no', '否'), ('pending', '待判定')], default='pending', max_length=20, verbose_name='割接是否超时')),
                ('timeout_reason', models.TextField(blank=True, verbose_name='超时原因')),
                ('cutover_result', models.CharField(blank=True, choices=[('completed', '完成'), ('incomplete', '未完成'), ('unsatisfactory', '不理想')], max_length=32, verbose_name='割接效果')),
                ('remaining_issues', models.TextField(blank=True, verbose_name='遗留问题')),
                ('rectification_status', models.CharField(blank=True, choices=[('not_required', '无需整改'), ('required', '需要整改'), ('duplicate_merged', '重复合并')], max_length=20, verbose_name='是否整改')),
                ('rectification_measures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('replace_power', '更换电源'), ('replace_battery', '更换电池'), ('battery_expansion', '电池扩容'), ('power_expansion', '电源扩容'), ('add_monitoring', '增加动环'), ('other', '其他')], max_length=30), blank=True, default=list, size=None, verbose_name='整改措施')),
                ('rectification_description', models.TextField(blank=True, verbose_name='措施描述')),
                ('rectification_subject', models.CharField(blank=True, choices=[('headquarters', '本部'), ('subsidiary', '子公司'), ('external', '外单位')], max_length=20, verbose_name='整改主体')),
                ('rectification_progress', models.CharField(blank=True, choices=[('not_started', '未实施'), ('in_progress', '进行中'), ('completed', '已完成'), ('suspended', '挂起')], max_length=20, verbose_name='整改进度')),
                ('planned_completion_time', models.DateTimeField(blank=True, null=True, verbose_name='计划完成时间')),
                ('actual_completion_time', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('rectification_completion_description', models.TextField(blank=True, verbose_name='整改完成情况描述')),
                ('planned_impact_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='预计影响时长（分钟）')),
                ('comments', models.TextField(blank=True, verbose_name='评论')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutover_tasks', to='netbox_contract.contract', verbose_name='代维/租赁合同')),
                ('handling_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_cutover_tasks', to='netbox_contract.serviceprovider', verbose_name='代维方/租赁方')),
                ('interruption_location', models.ManyToManyField(blank=True, related_name='cutover_tasks_z', to='dcim.site', verbose_name='割接影响Z端站点')),
                ('interruption_location_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_tasks_a', to='dcim.site', verbose_name='割接位置A端站点')),
                ('line_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_cutover_tasks', to=settings.AUTH_USER_MODEL, verbose_name='线路主管')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_cutover_tasks', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '割接管理',
                'verbose_name_plural': '割接管理',
                'ordering': ('-registered_at', '-pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
