# Generated by Codex on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models


FORWARD_SQL = """
DO $$
BEGIN
    -- Preserve deployments where 0067 created a legacy province text column.
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province_text'
    ) THEN
        ALTER TABLE netbox_otnfaults_cutovertask RENAME COLUMN province TO province_text;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province_id'
    ) THEN
        ALTER TABLE netbox_otnfaults_cutovertask ADD COLUMN province_id bigint NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province_text'
    ) THEN
        UPDATE netbox_otnfaults_cutovertask AS cutover
        SET province_id = region.id
        FROM dcim_region AS region
        WHERE cutover.province_id IS NULL
          AND cutover.province_text <> ''
          AND region.name = cutover.province_text;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'netbox_otnfaults_cutovertask_province_id_fk'
    ) THEN
        ALTER TABLE netbox_otnfaults_cutovertask
        ADD CONSTRAINT netbox_otnfaults_cutovertask_province_id_fk
        FOREIGN KEY (province_id) REFERENCES dcim_region(id)
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS netbox_otnfaults_cutovertask_province_id_idx
ON netbox_otnfaults_cutovertask (province_id);
"""


REVERSE_SQL = """
DROP INDEX IF EXISTS netbox_otnfaults_cutovertask_province_id_idx;

ALTER TABLE netbox_otnfaults_cutovertask
DROP CONSTRAINT IF EXISTS netbox_otnfaults_cutovertask_province_id_fk;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province_id'
    ) THEN
        ALTER TABLE netbox_otnfaults_cutovertask DROP COLUMN province_id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province_text'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province'
    ) THEN
        ALTER TABLE netbox_otnfaults_cutovertask RENAME COLUMN province_text TO province;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_otnfaults', '0067_cutovertask'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='cutovertask',
                    name='province',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='cutover_tasks',
                        to='dcim.region',
                        verbose_name='省份',
                    ),
                ),
            ],
        ),
    ]
