# Generated by Django on 2026-05-18

from django.db import migrations

FORWARD_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'netbox_otnfaults_cutovertask'
          AND column_name = 'province_text'
    ) THEN
        ALTER TABLE netbox_otnfaults_cutovertask ALTER COLUMN province_text DROP NOT NULL;
    END IF;
END $$;
"""

REVERSE_SQL = """
DO $$
BEGIN
    -- Reverse operation left empty to prevent breaking if rolling back
END $$;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0068_cutovertask_province_fk'),
    ]

    operations = [
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
