# Generated by Codex on 2026-05-19

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_otnfaults', '0070_cutovertask_drop_legacy_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoverImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('service_type', models.CharField(choices=[('bare_fiber', '裸纤业务'), ('circuit', '电路业务')], default='bare_fiber', max_length=20, verbose_name='业务类型')),
                ('business_impact', models.CharField(choices=[('interrupted', '业务中断'), ('not_interrupted', '业务未中断')], default='interrupted', max_length=20, verbose_name='业务影响')),
                ('service_interruption_time', models.DateTimeField(verbose_name='业务中断时间')),
                ('service_recovery_time', models.DateTimeField(blank=True, null=True, verbose_name='业务恢复时间')),
                ('comments', models.TextField(blank=True, verbose_name='评论')),
                ('bare_fiber_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutover_impacts', to='netbox_otnfaults.barefiberservice', verbose_name='裸纤业务')),
                ('circuit_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutover_impacts', to='netbox_otnfaults.circuitservice', verbose_name='电路业务')),
                ('cutover_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='netbox_otnfaults.cutovertask', verbose_name='割接任务')),

                ('service_site_a', models.ForeignKey(blank=True, help_text='仅裸纤业务时使用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutover_impact_service_site_a', to='dcim.site', verbose_name='业务站点A')),
                ('service_site_z', models.ManyToManyField(blank=True, help_text='仅裸纤业务时使用，可选择多个Z端站点', related_name='cutover_impact_service_site_z', to='dcim.site', verbose_name='业务站点Z')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '割接影响业务',
                'verbose_name_plural': '割接影响业务',
                'ordering': ('-service_interruption_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='cutoverimpact',
            constraint=models.UniqueConstraint(condition=models.Q(('bare_fiber_service__isnull', False)), fields=('cutover_task', 'bare_fiber_service'), name='unique_cutover_bare_fiber', violation_error_message='此割接任务下已经有该裸纤业务，不能重复添加。'),
        ),
        migrations.AddConstraint(
            model_name='cutoverimpact',
            constraint=models.UniqueConstraint(condition=models.Q(('circuit_service__isnull', False)), fields=('cutover_task', 'circuit_service'), name='unique_cutover_circuit', violation_error_message='此割接任务下已经有该电路业务，不能重复添加。'),
        ),
    ]
