# Generated by Codex on 2026-06-03

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0001_initial'),
        ('extras', '0001_initial'),
        ('netbox_otnfaults', '0075_otnfault_source_cutover_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, verbose_name='重保标题')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('description', models.TextField(verbose_name='重保描述/通知')),
                ('bare_fiber_services', models.ManyToManyField(blank=True, related_name='heavy_duties', to='netbox_otnfaults.barefiberservice', verbose_name='保障裸纤')),
                ('circuit_services', models.ManyToManyField(blank=True, related_name='heavy_duties', to='netbox_otnfaults.circuitservice', verbose_name='保障电路')),
                ('sites', models.ManyToManyField(blank=True, related_name='heavy_duties', to='dcim.site', verbose_name='保障站点')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '重要保障',
                'verbose_name_plural': '重要保障',
                'ordering': ('-start_time', '-pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
