# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0076_heavyduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavyduty',
            name='comments',
            field=models.TextField(blank=True, verbose_name='评论'),
        ),
    ]
