# Generated by Antigravity on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0078_alter_cutovertask_related_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutovertask',
            name='cutover_type',
            field=models.CharField(default='fiber', max_length=50, verbose_name='割接类型'),
        ),
    ]
