# Generated by Antigravity on 2026-06-09

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


def migrate_related_customers_to_impacts(apps, schema_editor):
    CutoverTask = apps.get_model('netbox_otnfaults', 'CutoverTask')
    CutoverImpact = apps.get_model('netbox_otnfaults', 'CutoverImpact')
    BareFiberService = apps.get_model('netbox_otnfaults', 'BareFiberService')

    for task in CutoverTask.objects.all():
        customers = task.related_customers
        if not customers or not isinstance(customers, list):
            continue

        for item in customers:
            if not isinstance(item, dict):
                continue

            service_id = item.get('service_id') or item.get('id')
            if not service_id:
                continue

            # 验证 BareFiberService 存在
            try:
                service = BareFiberService.objects.get(pk=service_id)
            except BareFiberService.DoesNotExist:
                continue

            is_coordinated = item.get('is_coordinated', False)
            coordination_status = 'approved' if is_coordinated else 'unapproved'

            # planned_cutover_time 可能为 null，若为 null 则 fallback 到 registered_at 乃至当前时间
            interruption_time = task.planned_cutover_time or task.registered_at or timezone.now()

            impact, created = CutoverImpact.objects.get_or_create(
                cutover_task=task,
                bare_fiber_service=service,
                defaults={
                    'service_type': 'bare_fiber',
                    'service_site_a': task.interruption_location_a,
                    'service_interruption_time': interruption_time,
                    'coordination_status': coordination_status,
                }
            )

            if not created:
                impact.coordination_status = coordination_status
                impact.save()


def reverse_migrate_related_customers(apps, schema_editor):
    # 反向迁移逻辑：如果回滚迁移，可将 CutoverImpact 记录塞回 related_customers
    CutoverTask = apps.get_model('netbox_otnfaults', 'CutoverTask')
    CutoverImpact = apps.get_model('netbox_otnfaults', 'CutoverImpact')

    for task in CutoverTask.objects.all():
        customers = []
        for impact in CutoverImpact.objects.filter(cutover_task=task, service_type='bare_fiber'):
            if not impact.bare_fiber_service:
                continue
            customers.append({
                'service_id': impact.bare_fiber_service.pk,
                'tenant': impact.bare_fiber_service.tenant_group.name if impact.bare_fiber_service.tenant_group else '',
                'business': impact.bare_fiber_service.name,
                'is_coordinated': impact.coordination_status == 'approved',
                'time': '',
            })
        task.related_customers = customers
        task.save(update_fields=['related_customers'])


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0079_cutovertask_cutover_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoverimpact',
            name='coordination_status',
            field=models.CharField(default='unapproved', max_length=32, verbose_name='协调状态'),
        ),
        migrations.RunPython(
            code=migrate_related_customers_to_impacts,
            reverse_code=reverse_migrate_related_customers,
        ),
        migrations.RemoveField(
            model_name='cutovertask',
            name='related_customers',
        ),
    ]
