# Generated by Django 5.2.6 on 2026-06-10 06:15

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_otnfaults', '0083_heavyduty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavyduty',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
