# Generated by Django 5.2.6 on 2026-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0084_alter_heavyduty_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutovertask',
            name='interruption_location',
            field=models.ManyToManyField(blank=True, related_name='cutover_tasks_z', to='dcim.site', verbose_name='割接位置Z端站点'),
        ),
    ]
