# Generated by Django 6.0.5 on 2026-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0088_alter_otnfault_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otnfaultimpact',
            name='business_impact',
            field=models.CharField(blank=True, default='interrupted', max_length=20),
        ),
        migrations.AlterField(
            model_name='otnfaultimpact',
            name='service_interruption_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
