# Generated by Django 6.0.5 on 2026-06-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otnfaults', '0089_alter_otnfaultimpact_business_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoverimpact',
            name='business_impact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
